# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FDTD-GUI.ui'
#
# Created: Wed Apr 23 19:12:56 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName(_fromUtf8("MainWidget"))
        MainWidget.resize(686, 429)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWidget.sizePolicy().hasHeightForWidth())
        MainWidget.setSizePolicy(sizePolicy)
        self.tabWidget = QtGui.QTabWidget(MainWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 691, 431))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_Basic = QtGui.QWidget()
        self.tab_Basic.setObjectName(_fromUtf8("tab_Basic"))
        self.groupBox_Coordinate = QtGui.QGroupBox(self.tab_Basic)
        self.groupBox_Coordinate.setGeometry(QtCore.QRect(30, 30, 251, 161))
        self.groupBox_Coordinate.setObjectName(_fromUtf8("groupBox_Coordinate"))
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox_Coordinate)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 56, 101))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.groupBox_Coordinate)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(89, 40, 111, 101))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lineEdit_CS_X = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_CS_X.setObjectName(_fromUtf8("lineEdit_CS_X"))
        self.verticalLayout_2.addWidget(self.lineEdit_CS_X)
        self.lineEdit_CS_Y = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_CS_Y.setObjectName(_fromUtf8("lineEdit_CS_Y"))
        self.verticalLayout_2.addWidget(self.lineEdit_CS_Y)
        self.lineEdit_CS_Z = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_CS_Z.setObjectName(_fromUtf8("lineEdit_CS_Z"))
        self.verticalLayout_2.addWidget(self.lineEdit_CS_Z)
        self.lineEdit_CS_GridSize = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_CS_GridSize.setObjectName(_fromUtf8("lineEdit_CS_GridSize"))
        self.verticalLayout_2.addWidget(self.lineEdit_CS_GridSize)
        self.groupBox_TimeStep = QtGui.QGroupBox(self.tab_Basic)
        self.groupBox_TimeStep.setGeometry(QtCore.QRect(30, 210, 251, 121))
        self.groupBox_TimeStep.setObjectName(_fromUtf8("groupBox_TimeStep"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.groupBox_TimeStep)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 30, 71, 61))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_3.addWidget(self.label_6)
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.groupBox_TimeStep)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(100, 30, 121, 61))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lineEdit_TS_Width = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_TS_Width.setObjectName(_fromUtf8("lineEdit_TS_Width"))
        self.verticalLayout_4.addWidget(self.lineEdit_TS_Width)
        self.lineEdit_TS_Number = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_TS_Number.setObjectName(_fromUtf8("lineEdit_TS_Number"))
        self.verticalLayout_4.addWidget(self.lineEdit_TS_Number)
        self.groupBox_Source = QtGui.QGroupBox(self.tab_Basic)
        self.groupBox_Source.setGeometry(QtCore.QRect(310, 60, 341, 271))
        self.groupBox_Source.setObjectName(_fromUtf8("groupBox_Source"))
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.groupBox_Source)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(30, 40, 141, 61))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_5.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_5.addWidget(self.label_8)
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.groupBox_Source)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(180, 40, 121, 61))
        self.verticalLayoutWidget_6.setObjectName(_fromUtf8("verticalLayoutWidget_6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.lineEdit_SC_CentralFreq = QtGui.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_SC_CentralFreq.setObjectName(_fromUtf8("lineEdit_SC_CentralFreq"))
        self.verticalLayout_6.addWidget(self.lineEdit_SC_CentralFreq)
        self.lineEdit_SC_BandWidth = QtGui.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_SC_BandWidth.setObjectName(_fromUtf8("lineEdit_SC_BandWidth"))
        self.verticalLayout_6.addWidget(self.lineEdit_SC_BandWidth)
        self.groupBox_SourcePosition = QtGui.QGroupBox(self.groupBox_Source)
        self.groupBox_SourcePosition.setGeometry(QtCore.QRect(30, 120, 211, 131))
        self.groupBox_SourcePosition.setObjectName(_fromUtf8("groupBox_SourcePosition"))
        self.verticalLayoutWidget_7 = QtGui.QWidget(self.groupBox_SourcePosition)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(20, 30, 21, 71))
        self.verticalLayoutWidget_7.setObjectName(_fromUtf8("verticalLayoutWidget_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_12 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_7.addWidget(self.label_12)
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_7.addWidget(self.label_11)
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_7.addWidget(self.label_10)
        self.verticalLayoutWidget_8 = QtGui.QWidget(self.groupBox_SourcePosition)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(50, 30, 101, 74))
        self.verticalLayoutWidget_8.setObjectName(_fromUtf8("verticalLayoutWidget_8"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.lineEdit_SCP_X = QtGui.QLineEdit(self.verticalLayoutWidget_8)
        self.lineEdit_SCP_X.setObjectName(_fromUtf8("lineEdit_SCP_X"))
        self.verticalLayout_8.addWidget(self.lineEdit_SCP_X)
        self.lineEdit_SCP_Y = QtGui.QLineEdit(self.verticalLayoutWidget_8)
        self.lineEdit_SCP_Y.setObjectName(_fromUtf8("lineEdit_SCP_Y"))
        self.verticalLayout_8.addWidget(self.lineEdit_SCP_Y)
        self.lineEdit_SCP_Z = QtGui.QLineEdit(self.verticalLayoutWidget_8)
        self.lineEdit_SCP_Z.setObjectName(_fromUtf8("lineEdit_SCP_Z"))
        self.verticalLayout_8.addWidget(self.lineEdit_SCP_Z)
        self.progressBar = QtGui.QProgressBar(self.tab_Basic)
        self.progressBar.setGeometry(QtCore.QRect(30, 360, 431, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.pushButton_Start = QtGui.QPushButton(self.tab_Basic)
        self.pushButton_Start.setGeometry(QtCore.QRect(490, 360, 75, 23))
        self.pushButton_Start.setObjectName(_fromUtf8("pushButton_Start"))
        self.pushButton_Stop = QtGui.QPushButton(self.tab_Basic)
        self.pushButton_Stop.setGeometry(QtCore.QRect(580, 360, 75, 23))
        self.pushButton_Stop.setObjectName(_fromUtf8("pushButton_Stop"))
        self.pushButton_New = QtGui.QPushButton(self.tab_Basic)
        self.pushButton_New.setGeometry(QtCore.QRect(310, 20, 75, 23))
        self.pushButton_New.setObjectName(_fromUtf8("pushButton_New"))
        self.pushButton_Open = QtGui.QPushButton(self.tab_Basic)
        self.pushButton_Open.setGeometry(QtCore.QRect(400, 20, 75, 23))
        self.pushButton_Open.setObjectName(_fromUtf8("pushButton_Open"))
        self.pushButton_Save = QtGui.QPushButton(self.tab_Basic)
        self.pushButton_Save.setGeometry(QtCore.QRect(490, 20, 75, 23))
        self.pushButton_Save.setObjectName(_fromUtf8("pushButton_Save"))
        self.pushButton_About = QtGui.QPushButton(self.tab_Basic)
        self.pushButton_About.setGeometry(QtCore.QRect(580, 20, 75, 23))
        self.pushButton_About.setObjectName(_fromUtf8("pushButton_About"))
        self.tabWidget.addTab(self.tab_Basic, _fromUtf8(""))
        self.tab_Scatterer = QtGui.QWidget()
        self.tab_Scatterer.setObjectName(_fromUtf8("tab_Scatterer"))
        self.groupBox_Brick = QtGui.QGroupBox(self.tab_Scatterer)
        self.groupBox_Brick.setGeometry(QtCore.QRect(20, 160, 261, 231))
        self.groupBox_Brick.setObjectName(_fromUtf8("groupBox_Brick"))
        self.verticalLayoutWidget_11 = QtGui.QWidget(self.groupBox_Brick)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(20, 30, 56, 151))
        self.verticalLayoutWidget_11.setObjectName(_fromUtf8("verticalLayoutWidget_11"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_15 = QtGui.QLabel(self.verticalLayoutWidget_11)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_11.addWidget(self.label_15)
        self.label_18 = QtGui.QLabel(self.verticalLayoutWidget_11)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_11.addWidget(self.label_18)
        self.label_17 = QtGui.QLabel(self.verticalLayoutWidget_11)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_11.addWidget(self.label_17)
        self.label_19 = QtGui.QLabel(self.verticalLayoutWidget_11)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_11.addWidget(self.label_19)
        self.label_16 = QtGui.QLabel(self.verticalLayoutWidget_11)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_11.addWidget(self.label_16)
        self.label_20 = QtGui.QLabel(self.verticalLayoutWidget_11)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_11.addWidget(self.label_20)
        self.verticalLayoutWidget_12 = QtGui.QWidget(self.groupBox_Brick)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(80, 31, 141, 152))
        self.verticalLayoutWidget_12.setObjectName(_fromUtf8("verticalLayoutWidget_12"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.lineEdit_SBK_Xmin = QtGui.QLineEdit(self.verticalLayoutWidget_12)
        self.lineEdit_SBK_Xmin.setObjectName(_fromUtf8("lineEdit_SBK_Xmin"))
        self.verticalLayout_12.addWidget(self.lineEdit_SBK_Xmin)
        self.lineEdit_SBK_Xmax = QtGui.QLineEdit(self.verticalLayoutWidget_12)
        self.lineEdit_SBK_Xmax.setObjectName(_fromUtf8("lineEdit_SBK_Xmax"))
        self.verticalLayout_12.addWidget(self.lineEdit_SBK_Xmax)
        self.lineEdit_SBK_Ymin = QtGui.QLineEdit(self.verticalLayoutWidget_12)
        self.lineEdit_SBK_Ymin.setObjectName(_fromUtf8("lineEdit_SBK_Ymin"))
        self.verticalLayout_12.addWidget(self.lineEdit_SBK_Ymin)
        self.lineEdit_SBK_Ymax = QtGui.QLineEdit(self.verticalLayoutWidget_12)
        self.lineEdit_SBK_Ymax.setObjectName(_fromUtf8("lineEdit_SBK_Ymax"))
        self.verticalLayout_12.addWidget(self.lineEdit_SBK_Ymax)
        self.lineEdit_SBK_Zmin = QtGui.QLineEdit(self.verticalLayoutWidget_12)
        self.lineEdit_SBK_Zmin.setObjectName(_fromUtf8("lineEdit_SBK_Zmin"))
        self.verticalLayout_12.addWidget(self.lineEdit_SBK_Zmin)
        self.lineEdit_SBK_Zmax = QtGui.QLineEdit(self.verticalLayoutWidget_12)
        self.lineEdit_SBK_Zmax.setObjectName(_fromUtf8("lineEdit_SBK_Zmax"))
        self.verticalLayout_12.addWidget(self.lineEdit_SBK_Zmax)
        self.toolButton = QtGui.QToolButton(self.groupBox_Brick)
        self.toolButton.setGeometry(QtCore.QRect(140, 190, 81, 21))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.groupBox_Medium = QtGui.QGroupBox(self.tab_Scatterer)
        self.groupBox_Medium.setGeometry(QtCore.QRect(20, 20, 261, 131))
        self.groupBox_Medium.setObjectName(_fromUtf8("groupBox_Medium"))
        self.verticalLayoutWidget_9 = QtGui.QWidget(self.groupBox_Medium)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(20, 30, 51, 80))
        self.verticalLayoutWidget_9.setObjectName(_fromUtf8("verticalLayoutWidget_9"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget_9)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_9.addWidget(self.label_9)
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget_9)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_9.addWidget(self.label_13)
        self.label_14 = QtGui.QLabel(self.verticalLayoutWidget_9)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_9.addWidget(self.label_14)
        self.verticalLayoutWidget_10 = QtGui.QWidget(self.groupBox_Medium)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(90, 30, 121, 80))
        self.verticalLayoutWidget_10.setObjectName(_fromUtf8("verticalLayoutWidget_10"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.lineEdit_SMD_Eps = QtGui.QLineEdit(self.verticalLayoutWidget_10)
        self.lineEdit_SMD_Eps.setObjectName(_fromUtf8("lineEdit_SMD_Eps"))
        self.verticalLayout_10.addWidget(self.lineEdit_SMD_Eps)
        self.lineEdit_SMD_Mu = QtGui.QLineEdit(self.verticalLayoutWidget_10)
        self.lineEdit_SMD_Mu.setObjectName(_fromUtf8("lineEdit_SMD_Mu"))
        self.verticalLayout_10.addWidget(self.lineEdit_SMD_Mu)
        self.lineEdit_SMD_Sigma = QtGui.QLineEdit(self.verticalLayoutWidget_10)
        self.lineEdit_SMD_Sigma.setObjectName(_fromUtf8("lineEdit_SMD_Sigma"))
        self.verticalLayout_10.addWidget(self.lineEdit_SMD_Sigma)
        self.treeView_Scatterer = QtGui.QTreeView(self.tab_Scatterer)
        self.treeView_Scatterer.setGeometry(QtCore.QRect(300, 30, 291, 361))
        self.treeView_Scatterer.setObjectName(_fromUtf8("treeView_Scatterer"))
        self.pushButton_SCT_Detail = QtGui.QPushButton(self.tab_Scatterer)
        self.pushButton_SCT_Detail.setGeometry(QtCore.QRect(600, 30, 75, 23))
        self.pushButton_SCT_Detail.setObjectName(_fromUtf8("pushButton_SCT_Detail"))
        self.pushButton_SCT_Delete = QtGui.QPushButton(self.tab_Scatterer)
        self.pushButton_SCT_Delete.setGeometry(QtCore.QRect(600, 70, 75, 23))
        self.pushButton_SCT_Delete.setObjectName(_fromUtf8("pushButton_SCT_Delete"))
        self.pushButton_SCT_Show = QtGui.QPushButton(self.tab_Scatterer)
        self.pushButton_SCT_Show.setGeometry(QtCore.QRect(600, 110, 75, 23))
        self.pushButton_SCT_Show.setObjectName(_fromUtf8("pushButton_SCT_Show"))
        self.pushButton_SCT_Wall = QtGui.QPushButton(self.tab_Scatterer)
        self.pushButton_SCT_Wall.setGeometry(QtCore.QRect(600, 180, 75, 23))
        self.pushButton_SCT_Wall.setObjectName(_fromUtf8("pushButton_SCT_Wall"))
        self.tabWidget.addTab(self.tab_Scatterer, _fromUtf8(""))
        self.tab_Receive = QtGui.QWidget()
        self.tab_Receive.setObjectName(_fromUtf8("tab_Receive"))
        self.groupBox_ReceivePosi = QtGui.QGroupBox(self.tab_Receive)
        self.groupBox_ReceivePosi.setGeometry(QtCore.QRect(40, 50, 221, 181))
        self.groupBox_ReceivePosi.setObjectName(_fromUtf8("groupBox_ReceivePosi"))
        self.verticalLayoutWidget_13 = QtGui.QWidget(self.groupBox_ReceivePosi)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(20, 40, 21, 80))
        self.verticalLayoutWidget_13.setObjectName(_fromUtf8("verticalLayoutWidget_13"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_13.setMargin(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_21 = QtGui.QLabel(self.verticalLayoutWidget_13)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_13.addWidget(self.label_21)
        self.label_22 = QtGui.QLabel(self.verticalLayoutWidget_13)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_13.addWidget(self.label_22)
        self.label_23 = QtGui.QLabel(self.verticalLayoutWidget_13)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_13.addWidget(self.label_23)
        self.verticalLayoutWidget_14 = QtGui.QWidget(self.groupBox_ReceivePosi)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(50, 40, 131, 80))
        self.verticalLayoutWidget_14.setObjectName(_fromUtf8("verticalLayoutWidget_14"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout_14.setMargin(0)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.lineEdit_RVP_X = QtGui.QLineEdit(self.verticalLayoutWidget_14)
        self.lineEdit_RVP_X.setObjectName(_fromUtf8("lineEdit_RVP_X"))
        self.verticalLayout_14.addWidget(self.lineEdit_RVP_X)
        self.lineEdit_RVP_Y = QtGui.QLineEdit(self.verticalLayoutWidget_14)
        self.lineEdit_RVP_Y.setObjectName(_fromUtf8("lineEdit_RVP_Y"))
        self.verticalLayout_14.addWidget(self.lineEdit_RVP_Y)
        self.lineEdit_RVP_Z = QtGui.QLineEdit(self.verticalLayoutWidget_14)
        self.lineEdit_RVP_Z.setObjectName(_fromUtf8("lineEdit_RVP_Z"))
        self.verticalLayout_14.addWidget(self.lineEdit_RVP_Z)
        self.pushButton_RVP_Add = QtGui.QPushButton(self.groupBox_ReceivePosi)
        self.pushButton_RVP_Add.setGeometry(QtCore.QRect(100, 140, 75, 23))
        self.pushButton_RVP_Add.setObjectName(_fromUtf8("pushButton_RVP_Add"))
        self.treeView_Receive = QtGui.QTreeView(self.tab_Receive)
        self.treeView_Receive.setGeometry(QtCore.QRect(300, 40, 331, 301))
        self.treeView_Receive.setObjectName(_fromUtf8("treeView_Receive"))
        self.pushButton_RV_Plot = QtGui.QPushButton(self.tab_Receive)
        self.pushButton_RV_Plot.setGeometry(QtCore.QRect(160, 260, 75, 23))
        self.pushButton_RV_Plot.setObjectName(_fromUtf8("pushButton_RV_Plot"))
        self.pushButton_RV_Export = QtGui.QPushButton(self.tab_Receive)
        self.pushButton_RV_Export.setGeometry(QtCore.QRect(60, 300, 75, 23))
        self.pushButton_RV_Export.setObjectName(_fromUtf8("pushButton_RV_Export"))
        self.pushButton_RV_ExportAll = QtGui.QPushButton(self.tab_Receive)
        self.pushButton_RV_ExportAll.setGeometry(QtCore.QRect(160, 300, 75, 23))
        self.pushButton_RV_ExportAll.setObjectName(_fromUtf8("pushButton_RV_ExportAll"))
        self.pushButton_RV_Delete = QtGui.QPushButton(self.tab_Receive)
        self.pushButton_RV_Delete.setGeometry(QtCore.QRect(60, 260, 75, 23))
        self.pushButton_RV_Delete.setObjectName(_fromUtf8("pushButton_RV_Delete"))
        self.tabWidget.addTab(self.tab_Receive, _fromUtf8(""))
        self.tab_Graphic = QtGui.QWidget()
        self.tab_Graphic.setObjectName(_fromUtf8("tab_Graphic"))
        self.groupBox_GR_CrossSection = QtGui.QGroupBox(self.tab_Graphic)
        self.groupBox_GR_CrossSection.setGeometry(QtCore.QRect(20, 30, 201, 141))
        self.groupBox_GR_CrossSection.setObjectName(_fromUtf8("groupBox_GR_CrossSection"))
        self.radioButton_GS_PlaneE = QtGui.QRadioButton(self.groupBox_GR_CrossSection)
        self.radioButton_GS_PlaneE.setGeometry(QtCore.QRect(30, 30, 89, 16))
        self.radioButton_GS_PlaneE.setObjectName(_fromUtf8("radioButton_GS_PlaneE"))
        self.radioButton_GS_PlaneH = QtGui.QRadioButton(self.groupBox_GR_CrossSection)
        self.radioButton_GS_PlaneH.setGeometry(QtCore.QRect(30, 60, 89, 16))
        self.radioButton_GS_PlaneH.setObjectName(_fromUtf8("radioButton_GS_PlaneH"))
        self.lineEdit_GS_Position = QtGui.QLineEdit(self.groupBox_GR_CrossSection)
        self.lineEdit_GS_Position.setGeometry(QtCore.QRect(90, 100, 71, 20))
        self.lineEdit_GS_Position.setObjectName(_fromUtf8("lineEdit_GS_Position"))
        self.label_24 = QtGui.QLabel(self.groupBox_GR_CrossSection)
        self.label_24.setGeometry(QtCore.QRect(23, 100, 61, 20))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_Graphic)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 190, 201, 131))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.formLayoutWidget = QtGui.QWidget(self.groupBox_8)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 40, 121, 80))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.radioButton_GSC_Ex = QtGui.QRadioButton(self.formLayoutWidget)
        self.radioButton_GSC_Ex.setObjectName(_fromUtf8("radioButton_GSC_Ex"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.radioButton_GSC_Ex)
        self.radioButton_GSC_Ey = QtGui.QRadioButton(self.formLayoutWidget)
        self.radioButton_GSC_Ey.setObjectName(_fromUtf8("radioButton_GSC_Ey"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.radioButton_GSC_Ey)
        self.radioButton_GSC_Hx = QtGui.QRadioButton(self.formLayoutWidget)
        self.radioButton_GSC_Hx.setObjectName(_fromUtf8("radioButton_GSC_Hx"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.radioButton_GSC_Hx)
        self.radioButton_GSC_Hy = QtGui.QRadioButton(self.formLayoutWidget)
        self.radioButton_GSC_Hy.setObjectName(_fromUtf8("radioButton_GSC_Hy"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.radioButton_GSC_Hy)
        self.radioButton_GSC_Ez = QtGui.QRadioButton(self.formLayoutWidget)
        self.radioButton_GSC_Ez.setObjectName(_fromUtf8("radioButton_GSC_Ez"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.radioButton_GSC_Ez)
        self.radioButton_GSC_Hz = QtGui.QRadioButton(self.formLayoutWidget)
        self.radioButton_GSC_Hz.setObjectName(_fromUtf8("radioButton_GSC_Hz"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.radioButton_GSC_Hz)
        self.graphicWidget = MatplotlibWidget(self.tab_Graphic)
        self.graphicWidget.setGeometry(QtCore.QRect(240, 30, 421, 341))
        self.graphicWidget.setObjectName(_fromUtf8("graphicWidget"))
        self.pushButton_GSC_Show = QtGui.QPushButton(self.tab_Graphic)
        self.pushButton_GSC_Show.setGeometry(QtCore.QRect(120, 340, 91, 31))
        self.pushButton_GSC_Show.setObjectName(_fromUtf8("pushButton_GSC_Show"))
        self.tabWidget.addTab(self.tab_Graphic, _fromUtf8(""))

        self.retranslateUi(MainWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.pushButton_New, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWidget.newSimulation)
        QtCore.QObject.connect(self.pushButton_Open, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWidget.openSimulation)
        QtCore.QObject.connect(self.pushButton_Save, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWidget.saveSimulation)
        QtCore.QObject.connect(self.pushButton_About, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWidget.about)
        QtCore.QObject.connect(self.pushButton_Start, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWidget.startSimulation)
        QtCore.QObject.connect(self.pushButton_Stop, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWidget.stopSimulation)
        QtCore.QObject.connect(self.toolButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWidget.addScatterer)
        QtCore.QObject.connect(self.pushButton_SCT_Detail, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWidget.scattererDetail)
        QtCore.QObject.connect(self.pushButton_SCT_Delete, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWidget.deleteScatterer)
        QtCore.QObject.connect(self.pushButton_SCT_Show, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWidget.showEnvirModel)
        QtCore.QObject.connect(self.pushButton_SCT_Wall, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWidget.setWall)
        QtCore.QObject.connect(self.pushButton_RVP_Add, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWidget.addReceivePoint)
        QtCore.QObject.connect(self.pushButton_RV_Delete, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWidget.deleteReceivePoint)
        QtCore.QObject.connect(self.pushButton_RV_Plot, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWidget.plotReceiveSignal)
        QtCore.QObject.connect(self.pushButton_RV_Export, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWidget.exportReceiveSignal)
        QtCore.QObject.connect(self.pushButton_RV_ExportAll, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWidget.exportAllReceive)
        QtCore.QObject.connect(self.pushButton_GSC_Show, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWidget.showFieldDistribution)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        MainWidget.setWindowTitle(_translate("MainWidget", "FDTD Simulation Platform", None))
        self.groupBox_Coordinate.setTitle(_translate("MainWidget", "Coordinate System", None))
        self.label_2.setText(_translate("MainWidget", "X axis", None))
        self.label_3.setText(_translate("MainWidget", "Y axis", None))
        self.label.setText(_translate("MainWidget", "Z axis", None))
        self.label_4.setText(_translate("MainWidget", "Grid size", None))
        self.groupBox_TimeStep.setTitle(_translate("MainWidget", "Time Step", None))
        self.label_5.setText(_translate("MainWidget", "Step width", None))
        self.label_6.setText(_translate("MainWidget", "Step number", None))
        self.groupBox_Source.setTitle(_translate("MainWidget", "Source", None))
        self.label_7.setText(_translate("MainWidget", "Central frequency (GHz)", None))
        self.label_8.setText(_translate("MainWidget", "Band width (GHz)", None))
        self.groupBox_SourcePosition.setTitle(_translate("MainWidget", "Position", None))
        self.label_12.setText(_translate("MainWidget", "X:", None))
        self.label_11.setText(_translate("MainWidget", "Y:", None))
        self.label_10.setText(_translate("MainWidget", "Z:", None))
        self.pushButton_Start.setText(_translate("MainWidget", "Start", None))
        self.pushButton_Stop.setText(_translate("MainWidget", "Stop", None))
        self.pushButton_New.setText(_translate("MainWidget", "New", None))
        self.pushButton_Open.setText(_translate("MainWidget", "Open", None))
        self.pushButton_Save.setText(_translate("MainWidget", "Save", None))
        self.pushButton_About.setText(_translate("MainWidget", "About", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Basic), _translate("MainWidget", "Basic", None))
        self.groupBox_Brick.setTitle(_translate("MainWidget", "Brick", None))
        self.label_15.setText(_translate("MainWidget", "X axis", None))
        self.label_18.setText(_translate("MainWidget", "   to:", None))
        self.label_17.setText(_translate("MainWidget", "Y axis", None))
        self.label_19.setText(_translate("MainWidget", "   to:", None))
        self.label_16.setText(_translate("MainWidget", "Z axis", None))
        self.label_20.setText(_translate("MainWidget", "   to:", None))
        self.toolButton.setText(_translate("MainWidget", "Add Brick", None))
        self.groupBox_Medium.setTitle(_translate("MainWidget", "Medium", None))
        self.label_9.setText(_translate("MainWidget", "epsilon", None))
        self.label_13.setText(_translate("MainWidget", "mu", None))
        self.label_14.setText(_translate("MainWidget", "sigma", None))
        self.pushButton_SCT_Detail.setText(_translate("MainWidget", "Detail", None))
        self.pushButton_SCT_Delete.setText(_translate("MainWidget", "Delete", None))
        self.pushButton_SCT_Show.setText(_translate("MainWidget", "Show", None))
        self.pushButton_SCT_Wall.setText(_translate("MainWidget", "Wall", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Scatterer), _translate("MainWidget", "Scatterer", None))
        self.groupBox_ReceivePosi.setTitle(_translate("MainWidget", "Position", None))
        self.label_21.setText(_translate("MainWidget", "X:", None))
        self.label_22.setText(_translate("MainWidget", "Y:", None))
        self.label_23.setText(_translate("MainWidget", "Z:", None))
        self.pushButton_RVP_Add.setText(_translate("MainWidget", "Add", None))
        self.pushButton_RV_Plot.setText(_translate("MainWidget", "Plot", None))
        self.pushButton_RV_Export.setText(_translate("MainWidget", "Export", None))
        self.pushButton_RV_ExportAll.setText(_translate("MainWidget", "Export All", None))
        self.pushButton_RV_Delete.setText(_translate("MainWidget", "Delete", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Receive), _translate("MainWidget", "Receive", None))
        self.groupBox_GR_CrossSection.setTitle(_translate("MainWidget", "Cross Section", None))
        self.radioButton_GS_PlaneE.setText(_translate("MainWidget", "E plane", None))
        self.radioButton_GS_PlaneH.setText(_translate("MainWidget", "H plane", None))
        self.label_24.setText(_translate("MainWidget", "Position", None))
        self.groupBox_8.setTitle(_translate("MainWidget", "Component", None))
        self.radioButton_GSC_Ex.setText(_translate("MainWidget", "Ex    ", None))
        self.radioButton_GSC_Ey.setText(_translate("MainWidget", "Ey", None))
        self.radioButton_GSC_Hx.setText(_translate("MainWidget", "Hx", None))
        self.radioButton_GSC_Hy.setText(_translate("MainWidget", "Hy", None))
        self.radioButton_GSC_Ez.setText(_translate("MainWidget", "Ez", None))
        self.radioButton_GSC_Hz.setText(_translate("MainWidget", "Hz", None))
        self.pushButton_GSC_Show.setText(_translate("MainWidget", "Show", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Graphic), _translate("MainWidget", "Graphic", None))

from matplotlibwidget import MatplotlibWidget
